# Numpy Indexing and Selection

In [1]:
import numpy as np

In [2]:
arr = np.arange(0,10)

In [3]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
arr[8]

8

In [5]:
arr[1:5]

array([1, 2, 3, 4])

In [6]:
arr[:]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [7]:
arr[5:]

array([5, 6, 7, 8, 9])

In [8]:
arr[:5]

array([0, 1, 2, 3, 4])

In [9]:
arr[0:5] = 100

In [10]:
arr

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9])

In [13]:
arr = np.arange(0,10)

In [14]:
sliceOfTheArray = arr[0:6]

In [31]:
sliceOfTheArray

array([99, 99, 99, 99, 99, 99])

In [32]:
sliceOfTheArray[:] = 99

In [33]:
sliceOfTheArray

array([99, 99, 99, 99, 99, 99])

In [34]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [35]:
arr_copy = arr.copy()

In [36]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

In [37]:
arr_copy[:5] = np.arange(5)

In [38]:
arr_copy

array([ 0,  1,  2,  3,  4, 99,  6,  7,  8,  9])

In [39]:
arr

array([99, 99, 99, 99, 99, 99,  6,  7,  8,  9])

# 2D Array

In [40]:
arr_2d = np.array([[5,10,15],[20,25,30],[35,40,45]])

In [41]:
arr_2d

array([[ 5, 10, 15],
       [20, 25, 30],
       [35, 40, 45]])

In [49]:
arr_2d[1][2]

30

In [50]:
arr_2d[1,2]

30

In [51]:
arr_2d[:2,1:]

array([[10, 15],
       [25, 30]])

In [67]:
arr_2d[:2]

array([[ 5, 10, 15],
       [20, 25, 30]])

In [70]:
arr = np.arange(1,11)

In [71]:
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [73]:
bool_arr = arr>5

In [74]:
bool_arr

array([False, False, False, False, False,  True,  True,  True,  True,
        True])

In [75]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [78]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [79]:
arr[arr<3]

array([1, 2])

In [80]:
arr_2d = np.arange(50).reshape(5,10)

In [82]:
arr_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [84]:
arr_2d[1:3,3:5]

array([[13, 14],
       [23, 24]])